### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by danimalweb** [mrchimp/sharelinks#3]
Can this get updated and published to NPM?

**Comment by mrchimp** [comment]
Yeah, can do. What updates are you looking for? Just UMD and such?

**Comment by danimalweb** [comment]
Exactly that. I'm going to use it in the latest Tofino build, via import ideally.

**Comment by danimalweb** [comment]
Forked it and did some messing around. Something is up with the jQuery binding. I got it to work, but it is  not right.

**Comment by mrchimp** [comment]
Cool. Let's have a chat about it sometime soon.

**Comment by mrchimp** [comment]
I removed jQuery and got the UMD working properly in 1.0.0.

**Comment by danimalweb** [comment]
I see the demo uses require, but not import. I ask I'm getting module not found via import 'sharelinks'

Can you confirm import is working as expected?

**Comment by danimalweb** [comment]
Is package.json missing a main entry?

**Comment by danimalweb** [comment]
I ended up using:

`import sharelinks from '../../js/sharelinks.js';` in the test and `import sharelinks from 'sharelinks/js/sharelinks';` from Tofino.

Maybe with a main entry we could get it to use the module name sharelinks,
