### ISSUE TITLE
Real platform name

### ISSUE THREAD

**Issue by danimalweb** [mrchimp/sharelinks#8]
The platform name in the code is all lowercase, which is fine for its internal use.

I need to get the platform name in correct formation, e.g. LinkedIn, Facebook, Google+ etc.

I'm mapping the platform name string to an array outside of sharelinks.

```
var SocialNetworks = {
        facebook  : 'Facebook',
        twitter   : 'Twitter',
        tumblr    : 'Tumblr',
        google    : 'Google+',
        pinterest : 'Pinterest',
        linkedin  : 'LinkedIn'
      };

      //Initialize sharelinks
      sharelinks('.share-links a', {
        onShare: function(data) {
          console.log(SocialNetworks[data.platform]);
        }
      });
```

Can we include the real names inside of this plugin? Bonus we could use them in the title attribute instead of lowercase version.

Want a PR?

**Comment by mrchimp** [comment]
Yeah sounds good to me. Should be straight forward enough. You can add them as a `name` attribute to the existing platforms object. Bonus points if you get rid of the tabs on line 119 :smile:

**Comment by danimalweb** [comment]
This will be possible in PR #10.
